EKF2_EV_CTRL = 15
EKF2_HGT_REF = Vision
EKF2_GPS_CTRL = 0
EKF2_EV_DELAY = 175.0ms
COM_ARM_WO_GPS = 1
EKF2_GPS_CHECK = 0
COM_POS_FS_EPH = 10.0
EKF2_MAG_TYPE = none
EKF2_BARO_CTRL = 0
SYS_HAS_BARO = 0
SYS_HAS_GPS = 0
SYS_HAS_MAG = 0